[package]
name = "friendsscout-calendar"
version = "0.1.0"
authors = ["Kohei Suzuki <eagletmt@gmail.com>"]

[dependencies]
clap = "2.31.2"
kuchiki = "0.7.0"
reqwest = "0.8.5"
url = "1.7.0"
regex = "1.0.0"
icalendar = "0.3.1"
chrono = "0.4.2"
selectors = "0.19.0"
